name: Publish package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      directory:
        description: The working directory of the package, useful for monorepos
        default: .
        type: string
      dry-run:
        description: Dry run (no publish)
        type: boolean
        default: true

jobs:
  npm-publish:
    uses: ./.github/workflows/ast-grep-release.yml
    with:
      directory: ${{ inputs.directory || '.' }}
      dry-run: ${{ inputs.dry-run || false }}
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
